import type { Metadata } from "next";
import "./globals.css";
import Header from "./Components/Common/Header/Header";
import { GetMe } from "./(Auth)/login/action";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await GetMe();
  console.log('🔍 Layout - User from GetMe:', user);

  return (
    <html lang="en">
      <body>
        <header>
          <Header user={user} />
        </header>
        <main>{children}</main>
        <footer>
          Footer
        </footer>
      </body>
    </html>
  );
}
